# SPDX-FileCopyrightText: 2026 Erlang Ecosystem Foundation
#
# SPDX-License-Identifier: Apache-2.0

defmodule Mix.Tasks.GenerateLumisCss do
  @shortdoc "Regenerates assets/vendor/css/lumis.css from the Lumis themes"

  @moduledoc """
  Generates `assets/vendor/css/lumis.css` — the token classes emitted by
  Lumis' `:html_linked` formatter (`.lumis` container, `.l-*` tokens) styled
  for both site themes.

  The light theme applies at `:root`; the dark theme is emitted twice,
  mirroring how every theme-dependent token in `assets/css/app.css` is
  declared: once under the explicit `[data-theme="dark"]` selection and once
  under the `prefers-color-scheme: dark` fallback for visitors who haven't
  picked a theme.

  Usage:

      mix generate_lumis_css
  """

  use Mix.Task

  @output_path "assets/vendor/css/lumis.css"
  @light_theme "github_light"
  @dark_theme "github_dark"

  # The app's codebox treatment (the values behind border-base-300 /
  # rounded-lg / bg-base-100 / p-3 / overflow-x-auto on the former slide-over
  # JSON pane), replacing the themes' own page-background colors.
  @container_style [
    {"background-color", "var(--color-base-100)"},
    {"border", "1px solid var(--color-base-300)"},
    {"border-radius", "0.5rem"},
    {"padding", "0.75rem"},
    {"overflow-x", "auto"}
  ]

  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("app.config")
    File.mkdir_p!(Path.dirname(@output_path))

    light = theme_css(@light_theme, "")
    dark = theme_css(@dark_theme, "[data-theme=\"dark\"]")
    dark_fallback = theme_css(@dark_theme, ":root:not([data-theme=\"light\"])")

    css = """
    /* Generated by `mix generate_lumis_css` — do not edit manually. */
    /* Themes: #{@light_theme} (light) / #{@dark_theme} (dark). */

    #{light}
    #{dark}
    @media (prefers-color-scheme: dark) {
    #{dark_fallback}
    }
    """

    File.write!(@output_path, css)
    Mix.shell().info("Written #{@output_path}")
  end

  defp theme_css(theme, scope) do
    Lumis.Theme.build_css!(theme, scope: scope, container_style: @container_style)
  end
end
