# SPDX-FileCopyrightText: 2026 2026 Erlang Ecosystem Foundation
#
# SPDX-License-Identifier: Apache-2.0

import Config

config :ash, policies: [show_policy_breakdowns?: true]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# The dev LiveReloader renders its reload/error overlay in a same-origin
# <iframe>, which the app-wide `frame-src 'none'` blocks. Loosen just that one
# directive to `'self'` for development. The `:directives` config value is a
# whole map (not deep-merged), so this restates the production map from
# config/config.exs with only `frame_src` changed — keep the two in sync.
config :plug_content_security_policy,
  directives: %{
    default_src: ~w('none'),
    script_src: ~w('self'),
    style_src: ~w('self'),
    img_src: ~w('self' data: https://github.com https://*.githubusercontent.com),
    font_src: ~w('self'),
    connect_src: ~w('self'),
    manifest_src: ~w('self'),
    base_uri: ~w('none'),
    form_action: ~w('self'),
    frame_ancestors: ~w('none'),
    frame_src: ~w('self'),
    object_src: ~w('none')
  }

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure your database
config :varsel, Varsel.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "varsel_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :varsel, Varsel.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM, tag: "AES.GCM.V1", key: Base.decode64!("bvVixCuGMqaxlGEZiUEAWISf5p8qlrmpT+EvGhAJi2A=")}
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :varsel, VarselWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "03e4VyftWvYtYjGop9u2I8Gqe+vY/d5WJxFc41MiX7SRqh7UVgNaE3aAt0Ta1QRS",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:varsel, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:varsel, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :varsel, VarselWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/varsel_web/router\.ex$",
      ~r"lib/varsel_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :varsel,
  dev_routes: true,
  token_signing_secret: "UEhqsoDaIGLdNpy47qra8ygp/06r0T7F",
  oauth2_issuer_url: "http://localhost:4000",
  # Audience of minted access tokens and the protected-resource identity
  # (RFC 8707): the bare host, covering every token-consuming surface
  # (/mcp, /gql); scopes, not audiences, separate the surfaces.
  oauth2_resource_url: "http://localhost:4000",
  oauth2_signing_secret: "3pTWxv0hnz+fyxgPVN3H4cR4+8yq+Iek0JGFdHw+64o"
