# SPDX-FileCopyrightText: 2026 2026 Erlang Ecosystem Foundation
#
# SPDX-License-Identifier: Apache-2.0

import Config

# Do not print debug messages in production
config :logger, level: :info

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Runtime production configuration, including reading

# Disable Swoosh Local Memory Storage
# of environment variables, is done on config/runtime.exs.
config :swoosh, local: false

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :varsel, VarselWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-transport-security"
# header (HSTS). We only ever serve over HTTPS, so opt into the strongest
# policy: a 2-year max-age with `includeSubDomains`, and `preload` so browsers
# ship with the host pinned to HTTPS (these are exactly the HSTS preload-list
# requirements — https://hstspreload.org). `:force_ssl` must be set at
# compile-time.
config :varsel, VarselWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    expires: 63_072_000,
    preload: true,
    subdomains: true,
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]
