defmodule Varsel.Repo.Migrations.AddChannelTagPrefix do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:case_package_channels) do
      add :tag_prefix, :text
    end
  end

  def down do
    alter table(:case_package_channels) do
      remove :tag_prefix
    end
  end
end
