defmodule Varsel.Repo.Migrations.AddIncludePrereleases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:case_affected_packages) do
      add :include_prereleases, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:case_affected_packages) do
      remove :include_prereleases
    end
  end
end
