defmodule Varsel.Repo.Migrations.AddCveRecordVersion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cve_records) do
      add :version, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:cve_records) do
      remove :version
    end
  end
end
