defmodule Varsel.Repo.Migrations.AddCaseInviteEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:case_invites) do
      add :email, :citext
      add :email_status, :text, null: false, default: "unavailable"
      add :emailed_at, :utc_datetime_usec
    end

    alter table(:case_invites) do
      modify :email_status, :text, null: false, default: nil
    end
  end

  def down do
    alter table(:case_invites) do
      remove :emailed_at
      remove :email_status
      remove :email
    end
  end
end
