defmodule Varsel.Repo.Migrations.AddHexReportIntake do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vulnerability_reports) do
      add :source, :text, null: false, default: "web"
    end

    create table(:report_participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :strategy, :text, null: false
      add :username, :citext, null: false
      add :name, :text
      add :email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :report_id,
          references(:vulnerability_reports,
            column: :id,
            name: "report_participants_report_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "report_participants_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:report_participants, [:report_id, :role, :strategy, :username],
             name: "report_participants_unique_report_handle_index"
           )

    create table(:report_participants_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end
  end

  def down do
    drop table(:report_participants_versions)

    drop constraint(:report_participants, "report_participants_report_id_fkey")

    drop constraint(:report_participants, "report_participants_user_id_fkey")

    drop_if_exists unique_index(:report_participants, [:report_id, :role, :strategy, :username],
                     name: "report_participants_unique_report_handle_index"
                   )

    drop table(:report_participants)

    alter table(:vulnerability_reports) do
      remove :source
    end
  end
end
