defmodule Varsel.Repo.Migrations.AddAccountDeletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:case_assignments_versions, "case_assignments_versions_user_id_fkey")

    alter table(:case_assignments_versions) do
      modify :user_id, :uuid
    end

    create index(:case_assignments_versions, [:user_id])

    drop constraint(:case_proposals_versions, "case_proposals_versions_user_id_fkey")

    alter table(:case_proposals_versions) do
      modify :user_id, :uuid
    end

    create index(:case_proposals_versions, [:user_id])

    drop constraint(:vulnerability_reports, "vulnerability_reports_reporter_id_fkey")

    alter table(:vulnerability_reports) do
      modify :reporter_id,
             references(:users,
               column: :id,
               name: "vulnerability_reports_reporter_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             ),
             null: true
    end

    drop constraint(:case_credits_versions, "case_credits_versions_user_id_fkey")

    alter table(:case_credits_versions) do
      modify :user_id, :uuid
    end

    create index(:case_credits_versions, [:user_id])

    drop constraint(:cve_records_versions, "cve_records_versions_user_id_fkey")

    alter table(:cve_records_versions) do
      modify :user_id, :uuid
    end

    create index(:cve_records_versions, [:user_id])

    drop constraint(:case_impacts_versions, "case_impacts_versions_user_id_fkey")

    alter table(:case_impacts_versions) do
      modify :user_id, :uuid
    end

    create index(:case_impacts_versions, [:user_id])

    drop constraint(
           :case_affected_packages_versions,
           "case_affected_packages_versions_user_id_fkey"
         )

    alter table(:case_affected_packages_versions) do
      modify :user_id, :uuid
    end

    create index(:case_affected_packages_versions, [:user_id])

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    alter table(:user_identities) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "user_identities_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:case_version_events_versions, "case_version_events_versions_user_id_fkey")

    alter table(:case_version_events_versions) do
      modify :user_id, :uuid
    end

    create index(:case_version_events_versions, [:user_id])

    drop constraint(:users_versions, "users_versions_user_id_fkey")

    alter table(:users_versions) do
      modify :user_id, :uuid
    end

    create index(:users_versions, [:user_id])

    drop constraint(:case_proposals, "case_proposals_resolved_by_id_fkey")

    drop constraint(:case_proposals, "case_proposals_author_id_fkey")

    alter table(:case_proposals) do
      modify :author_id,
             references(:users,
               column: :id,
               name: "case_proposals_author_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             ),
             null: true

      modify :resolved_by_id,
             references(:users,
               column: :id,
               name: "case_proposals_resolved_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop constraint(:api_keys_versions, "api_keys_versions_user_id_fkey")

    alter table(:api_keys_versions) do
      modify :user_id, :uuid
    end

    create index(:api_keys_versions, [:user_id])

    drop constraint(:case_comments, "case_comments_author_id_fkey")

    alter table(:case_comments) do
      modify :author_id,
             references(:users,
               column: :id,
               name: "case_comments_author_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             ),
             null: true
    end

    drop constraint(:case_references_versions, "case_references_versions_user_id_fkey")

    alter table(:case_references_versions) do
      modify :user_id, :uuid
    end

    create index(:case_references_versions, [:user_id])

    drop constraint(:tokens_versions, "tokens_versions_user_id_fkey")

    alter table(:tokens_versions) do
      modify :user_id, :uuid
    end

    create index(:tokens_versions, [:user_id])

    drop constraint(:case_comments_versions, "case_comments_versions_user_id_fkey")

    alter table(:case_comments_versions) do
      modify :user_id, :uuid
    end

    create index(:case_comments_versions, [:user_id])

    drop constraint(
           :case_package_channels_versions,
           "case_package_channels_versions_user_id_fkey"
         )

    alter table(:case_package_channels_versions) do
      modify :user_id, :uuid
    end

    create index(:case_package_channels_versions, [:user_id])

    drop constraint(:user_identities_versions, "user_identities_versions_user_id_fkey")

    alter table(:user_identities_versions) do
      modify :user_id, :uuid
    end

    create index(:user_identities_versions, [:user_id])

    drop constraint(:case_weaknesses_versions, "case_weaknesses_versions_user_id_fkey")

    alter table(:case_weaknesses_versions) do
      modify :user_id, :uuid
    end

    create index(:case_weaknesses_versions, [:user_id])

    drop constraint(:cases_versions, "cases_versions_user_id_fkey")

    alter table(:cases_versions) do
      modify :user_id, :uuid
    end

    create index(:cases_versions, [:user_id])

    drop constraint(
           :vulnerability_reports_versions,
           "vulnerability_reports_versions_user_id_fkey"
         )

    alter table(:vulnerability_reports_versions) do
      modify :user_id, :uuid
    end

    create index(:vulnerability_reports_versions, [:user_id])
  end

  def down do
    drop_if_exists index(:vulnerability_reports_versions, [:user_id])

    alter table(:vulnerability_reports_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "vulnerability_reports_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:cases_versions, [:user_id])

    alter table(:cases_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "cases_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:case_weaknesses_versions, [:user_id])

    alter table(:case_weaknesses_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_weaknesses_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:user_identities_versions, [:user_id])

    alter table(:user_identities_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "user_identities_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:case_package_channels_versions, [:user_id])

    alter table(:case_package_channels_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_package_channels_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:case_comments_versions, [:user_id])

    alter table(:case_comments_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_comments_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:tokens_versions, [:user_id])

    alter table(:tokens_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "tokens_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:case_references_versions, [:user_id])

    alter table(:case_references_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_references_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop constraint(:case_comments, "case_comments_author_id_fkey")

    alter table(:case_comments) do
      modify :author_id,
             references(:users,
               column: :id,
               name: "case_comments_author_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end

    drop_if_exists index(:api_keys_versions, [:user_id])

    alter table(:api_keys_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "api_keys_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop constraint(:case_proposals, "case_proposals_author_id_fkey")

    drop constraint(:case_proposals, "case_proposals_resolved_by_id_fkey")

    alter table(:case_proposals) do
      modify :resolved_by_id,
             references(:users,
               column: :id,
               name: "case_proposals_resolved_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "case_proposals_author_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end

    drop_if_exists index(:users_versions, [:user_id])

    alter table(:users_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "users_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:case_version_events_versions, [:user_id])

    alter table(:case_version_events_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_version_events_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    alter table(:user_identities) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "user_identities_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:case_affected_packages_versions, [:user_id])

    alter table(:case_affected_packages_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_affected_packages_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:case_impacts_versions, [:user_id])

    alter table(:case_impacts_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_impacts_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:cve_records_versions, [:user_id])

    alter table(:cve_records_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "cve_records_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:case_credits_versions, [:user_id])

    alter table(:case_credits_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_credits_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop constraint(:vulnerability_reports, "vulnerability_reports_reporter_id_fkey")

    alter table(:vulnerability_reports) do
      modify :reporter_id,
             references(:users,
               column: :id,
               name: "vulnerability_reports_reporter_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end

    drop_if_exists index(:case_proposals_versions, [:user_id])

    alter table(:case_proposals_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_proposals_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:case_assignments_versions, [:user_id])

    alter table(:case_assignments_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_assignments_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end
  end
end
