defmodule Varsel.Repo.Migrations.AddCweViews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cwe_view_memberships, primary_key: false) do
      add :view_id, :bigint, null: false, primary_key: true
      add :cwe_id, :bigint, null: false, primary_key: true
    end

    create table(:cwe_views, primary_key: false) do
      add :view_id, :bigint, null: false, primary_key: true
    end

    alter table(:cwe_view_memberships) do
      modify :view_id,
             references(:cwe_views,
               column: :view_id,
               name: "cwe_view_memberships_view_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :cwe_id,
             references(:cwe_weaknesses,
               column: :cwe_id,
               name: "cwe_view_memberships_cwe_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:cwe_views) do
      add :name, :text, null: false
      add :type, :text, null: false
      add :status, :text, null: false
      add :objective, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    # cwe_weakness_relationships is pure MITRE-derived catalog data, fully
    # resynced by the @reboot Oban schedule — existing rows may reference
    # view_ids that don't exist yet (cwe_views is empty at migration time),
    # which would fail the FK add below. Drop them now instead of trying to
    # backfill cwe_views; the next sync run repopulates everything.
    execute("DELETE FROM cwe_weakness_relationships", "")

    # Force the next boot's sync to actually re-download and re-process the
    # catalog rather than skipping on a stale If-Modified-Since match, which
    # would otherwise leave cwe_weakness_relationships empty until MITRE next
    # updates the feed.
    execute("DELETE FROM cwe_metadata", "")

    alter table(:cwe_weakness_relationships) do
      modify :view_id,
             references(:cwe_views,
               column: :view_id,
               name: "cwe_weakness_relationships_view_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute(
      "ALTER TABLE cwe_weakness_relationships ALTER CONSTRAINT cwe_weakness_relationships_view_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    create index(:cwe_weakness_relationships, [:view_id])
  end

  def down do
    drop_if_exists index(:cwe_weakness_relationships, [:view_id])

    drop constraint(:cwe_weakness_relationships, "cwe_weakness_relationships_view_id_fkey")

    alter table(:cwe_weakness_relationships) do
      modify :view_id, :bigint
    end

    alter table(:cwe_views) do
      remove :updated_at
      remove :inserted_at
      remove :objective
      remove :status
      remove :type
      remove :name
    end

    drop constraint(:cwe_view_memberships, "cwe_view_memberships_view_id_fkey")

    drop constraint(:cwe_view_memberships, "cwe_view_memberships_cwe_id_fkey")

    alter table(:cwe_view_memberships) do
      modify :cwe_id, :bigint
      modify :view_id, :bigint
    end

    drop table(:cwe_views)

    drop table(:cwe_view_memberships)
  end
end
