defmodule Varsel.Repo.Migrations.DropAffectedPackageDefaultStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:case_affected_packages) do
      remove :default_status
    end
  end

  def down do
    alter table(:case_affected_packages) do
      add :default_status, :text, null: false, default: "unaffected"
    end
  end
end
