defmodule Varsel.Repo.Migrations.FixCaseIdSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # `ALTER COLUMN ... SET EXPRESSION` would edit the column in place, but it
  # needs Postgres 18. Dropping and recreating costs nothing here: the column
  # is generated, so it rebuilds from the rows it always derived from.
  def up do
    execute("""
    ALTER TABLE cases DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    ALTER TABLE cases ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (
      setweight(to_tsvector('english', id::text), 'A') ||
      setweight(to_tsvector('english', replace(id::text, '-', ' ')), 'A') ||
      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description_md, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(technical_analysis_md, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(workarounds_md, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(solutions_md, '')), 'C')
    ) STORED
    """)

    # Dropping the column took its index with it.
    execute("""
    CREATE INDEX cases_search_vector_gin ON cases USING GIN (search_vector)
    """)
  end

  def down do
    execute("""
    ALTER TABLE cases DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    ALTER TABLE cases ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (
      setweight(to_tsvector('simple', id::text), 'A') ||
      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description_md, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(technical_analysis_md, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(workarounds_md, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(solutions_md, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX cases_search_vector_gin ON cases USING GIN (search_vector)
    """)
  end
end
