defmodule Varsel.Repo.Migrations.ResolveOauthByIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:users, [:name],
             name: "users_unique_mock_name_index",
             where: "(name IS NOT NULL AND name LIKE 'Mock %')"
           )
  end

  def down do
    drop_if_exists unique_index(:users, [:name], name: "users_unique_mock_name_index")
  end
end
