defmodule Varsel.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text
      add :github_id, :text
      add :github_handle, :text
      add :name, :text
      add :role, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    create table(:user_identities, primary_key: false) do
      add :refresh_token, :text
      add :access_token_expires_at, :utc_datetime_usec
      add :access_token, :text
      add :uid, :text, null: false
      add :strategy, :text, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:user_identities, [:strategy, :uid],
             name: "user_identities_unique_on_strategy_and_uid_index"
           )

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:cwe_weaknesses, primary_key: false) do
      add :cwe_id, :bigint, null: false, primary_key: true
      add :name, :text, null: false
      add :abstraction, :text, null: false
      add :status, :text, null: false
      add :description, :text, null: false
      add :extended_description, :text
      add :potential_mitigations, :text
      add :common_consequences, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:cwe_weakness_relationships, primary_key: false) do
      add :source_cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "cwe_weakness_relationships_source_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false

      add :target_cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "cwe_weakness_relationships_target_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false

      add :nature, :text, null: false, primary_key: true
      add :view_id, :bigint, null: false, primary_key: true
      add :ordinal, :text
    end

    create table(:cwe_metadata, primary_key: false) do
      add :singleton_key, :text, null: false, default: "singleton", primary_key: true
      add :last_modified, :text
      add :last_synced_at, :utc_datetime
    end

    create table(:cve_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reservation_json, :map
      add :cve_json, :map
      add :last_synced_at, :utc_datetime
      add :rejected_at, :utc_datetime
      add :rejection_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "reserved"
    end

    create unique_index(
             :cve_records,
             ["(coalesce(cve_json->'cveMetadata'->>'cveId', reservation_json->>'cve_id'))"],
             name: "cve_records_unique_cve_id_index"
           )

    create table(:capec_metadata, primary_key: false) do
      add :singleton_key, :text, null: false, default: "singleton", primary_key: true
      add :last_modified, :text
      add :last_synced_at, :utc_datetime
    end

    create table(:capec_attack_patterns, primary_key: false) do
      add :capec_id, :bigint, null: false, primary_key: true
      add :name, :text, null: false
      add :abstraction, :text, null: false
      add :status, :text, null: false
      add :description, :text
      add :extended_description, :text
      add :likelihood_of_attack, :text
      add :typical_severity, :text
      add :prerequisites, :text
      add :mitigations, :text
      add :consequences, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:capec_attack_pattern_weaknesses, primary_key: false) do
      add :capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "capec_attack_pattern_weaknesses_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false

      add :cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "capec_attack_pattern_weaknesses_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false
    end

    create table(:capec_attack_pattern_relationships, primary_key: false) do
      add :source_capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "capec_attack_pattern_relationships_source_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false

      add :target_capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "capec_attack_pattern_relationships_target_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false

      add :nature, :text, null: false, primary_key: true
    end

    execute(
      "ALTER TABLE capec_attack_pattern_relationships ALTER CONSTRAINT capec_attack_pattern_relationships_target_capec_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute("""
    ALTER TABLE capec_attack_patterns
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(extended_description, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(prerequisites, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(mitigations, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(consequences, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX capec_attack_patterns_search_vector_gin ON capec_attack_patterns USING GIN (search_vector)
    """)

    execute("""
    CREATE FUNCTION cve_record_search_vector(cve_json jsonb)
    RETURNS tsvector
    LANGUAGE sql
    IMMUTABLE PARALLEL SAFE
    AS $$
      SELECT
        setweight(to_tsvector('english', coalesce(cve_json->'cveMetadata'->>'cveId', '')), 'A') ||
        setweight(to_tsvector('english', coalesce(cve_json->'containers'->'cna'->>'title', '')), 'A') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(d->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'descriptions', '[]'::jsonb)) AS d),
          ''
        )), 'B') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(
             coalesce(a->>'packageName', '') || ' ' ||
             coalesce(a->>'product', '') || ' ' ||
             coalesce(a->>'vendor', ''),
             ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'affected', '[]'::jsonb)) AS a),
          ''
        )), 'B') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(w->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'workarounds', '[]'::jsonb)) AS w),
          ''
        )), 'C') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(c->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'configurations', '[]'::jsonb)) AS c),
          ''
        )), 'C') ||
        setweight(to_tsvector('simple', regexp_replace(cve_json::text, '[^a-zA-Z0-9 ]', ' ', 'g')), 'D')
    $$
    """)

    execute("""
    ALTER TABLE cve_records ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (cve_record_search_vector(coalesce(cve_json, '{}'::jsonb))) STORED
    """)

    execute("""
    CREATE INDEX cve_records_search_vector_gin ON cve_records USING GIN (search_vector)
    """)

    execute("""
    CREATE INDEX cve_records_affected_gin ON cve_records USING GIN ((cve_json->'containers'->'cna'->'affected'))
    """)

    execute(
      "ALTER TABLE cwe_weakness_relationships ALTER CONSTRAINT cwe_weakness_relationships_target_cwe_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute("""
    ALTER TABLE cwe_weaknesses
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(extended_description, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(potential_mitigations, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(common_consequences, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX cwe_weaknesses_search_vector_gin ON cwe_weaknesses USING GIN (search_vector)
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS cwe_weaknesses_search_vector_gin
    """)

    execute("""
    ALTER TABLE cwe_weaknesses DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    DROP INDEX IF EXISTS cve_records_affected_gin
    """)

    execute("""
    DROP INDEX IF EXISTS cve_records_search_vector_gin
    """)

    execute("""
    ALTER TABLE cve_records DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    DROP FUNCTION IF EXISTS cve_record_search_vector(jsonb)
    """)

    execute("""
    DROP INDEX IF EXISTS capec_attack_patterns_search_vector_gin
    """)

    execute("""
    ALTER TABLE capec_attack_patterns DROP COLUMN IF EXISTS search_vector
    """)

    drop constraint(
           :capec_attack_pattern_relationships,
           "capec_attack_pattern_relationships_source_capec_id_fkey"
         )

    drop constraint(
           :capec_attack_pattern_relationships,
           "capec_attack_pattern_relationships_target_capec_id_fkey"
         )

    drop table(:capec_attack_pattern_relationships)

    drop constraint(
           :capec_attack_pattern_weaknesses,
           "capec_attack_pattern_weaknesses_capec_id_fkey"
         )

    drop constraint(
           :capec_attack_pattern_weaknesses,
           "capec_attack_pattern_weaknesses_cwe_id_fkey"
         )

    drop table(:capec_attack_pattern_weaknesses)

    drop table(:capec_attack_patterns)

    drop table(:capec_metadata)

    drop_if_exists unique_index(
                     :cve_records,
                     [
                       "(coalesce(cve_json->'cveMetadata'->>'cveId', reservation_json->>'cve_id'))"
                     ],
                     name: "cve_records_unique_cve_id_index"
                   )

    drop table(:cve_records)

    drop table(:cwe_metadata)

    drop constraint(:cwe_weakness_relationships, "cwe_weakness_relationships_source_cwe_id_fkey")

    drop constraint(:cwe_weakness_relationships, "cwe_weakness_relationships_target_cwe_id_fkey")

    drop table(:cwe_weakness_relationships)

    drop table(:cwe_weaknesses)

    drop table(:tokens)

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    drop_if_exists unique_index(:user_identities, [:strategy, :uid],
                     name: "user_identities_unique_on_strategy_and_uid_index"
                   )

    drop table(:user_identities)

    drop_if_exists unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    drop table(:users)

    execute(
      "ALTER TABLE cwe_weakness_relationships ALTER CONSTRAINT cwe_weakness_relationships_target_cwe_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute(
      "ALTER TABLE capec_attack_pattern_relationships ALTER CONSTRAINT capec_attack_pattern_relationships_target_capec_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )
  end
end
