defmodule Varsel.Repo.Migrations.AddAffectedPackageDefaultStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:case_affected_packages) do
      add :default_status, :text, null: false, default: "unaffected"
    end

    # Packages introduced at the erlang/otp root commit (with no explicit
    # version placing the boundary) published an unknown era as a sentinel
    # range; the stored attribute carries that claim now. Bumping updated_at
    # outdates their cached derivation, which still holds the sentinel shape.
    execute """
    UPDATE case_affected_packages
    SET default_status = 'unknown', updated_at = clock_timestamp()
    WHERE id IN (
      SELECT affected_package_id FROM case_version_events
      WHERE event = 'introduced'
        AND commit_sha = '84adefa331c4159d432d22840663c38f155cd4c1'
        AND version IS NULL
    )
    """
  end

  def down do
    alter table(:case_affected_packages) do
      remove :default_status
    end
  end
end
