defmodule CveManagement.Repo.Migrations.AddCapec do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cwe_weaknesses) do
      remove :related_weaknesses
    end

    create table(:cwe_weakness_relationships, primary_key: false) do
      add :source_cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "cwe_weakness_relationships_source_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :target_cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "cwe_weakness_relationships_target_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :nature, :text, null: false, primary_key: true
      add :view_id, :bigint, null: false, primary_key: true
      add :ordinal, :text
    end

    create table(:capec_metadata, primary_key: false) do
      add :singleton_key, :text, null: false, default: "singleton", primary_key: true
      add :last_modified, :text
      add :last_synced_at, :utc_datetime
    end

    create table(:capec_attack_patterns, primary_key: false) do
      add :capec_id, :bigint, null: false, primary_key: true
      add :name, :text, null: false
      add :abstraction, :text, null: false
      add :status, :text, null: false
      add :description, :text
      add :extended_description, :text
      add :likelihood_of_attack, :text
      add :typical_severity, :text
      add :prerequisites, :text
      add :mitigations, :text
      add :consequences, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:capec_attack_pattern_weaknesses, primary_key: false) do
      add :capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "capec_attack_pattern_weaknesses_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "capec_attack_pattern_weaknesses_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create table(:capec_attack_pattern_relationships, primary_key: false) do
      add :source_capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "capec_attack_pattern_relationships_source_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :target_capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "capec_attack_pattern_relationships_target_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :nature, :text, null: false, primary_key: true
    end

    execute(
      "ALTER TABLE capec_attack_pattern_relationships ALTER CONSTRAINT capec_attack_pattern_relationships_target_capec_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute("""
    ALTER TABLE capec_attack_patterns
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(extended_description, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(prerequisites, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(mitigations, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(consequences, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX capec_attack_patterns_search_vector_gin ON capec_attack_patterns USING GIN (search_vector)
    """)

    execute(
      "ALTER TABLE cwe_weakness_relationships ALTER CONSTRAINT cwe_weakness_relationships_target_cwe_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS capec_attack_patterns_search_vector_gin
    """)

    execute("""
    ALTER TABLE capec_attack_patterns DROP COLUMN IF EXISTS search_vector
    """)

    drop constraint(
           :capec_attack_pattern_relationships,
           "capec_attack_pattern_relationships_source_capec_id_fkey"
         )

    drop constraint(
           :capec_attack_pattern_relationships,
           "capec_attack_pattern_relationships_target_capec_id_fkey"
         )

    drop table(:capec_attack_pattern_relationships)

    drop constraint(
           :capec_attack_pattern_weaknesses,
           "capec_attack_pattern_weaknesses_capec_id_fkey"
         )

    drop constraint(
           :capec_attack_pattern_weaknesses,
           "capec_attack_pattern_weaknesses_cwe_id_fkey"
         )

    drop table(:capec_attack_pattern_weaknesses)

    drop table(:capec_attack_patterns)

    drop table(:capec_metadata)

    drop constraint(:cwe_weakness_relationships, "cwe_weakness_relationships_source_cwe_id_fkey")

    drop constraint(:cwe_weakness_relationships, "cwe_weakness_relationships_target_cwe_id_fkey")

    drop table(:cwe_weakness_relationships)

    alter table(:cwe_weaknesses) do
      add :related_weaknesses, {:array, :map}, null: false, default: []
    end

    execute(
      "ALTER TABLE cwe_weakness_relationships ALTER CONSTRAINT cwe_weakness_relationships_target_cwe_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute(
      "ALTER TABLE capec_attack_pattern_relationships ALTER CONSTRAINT capec_attack_pattern_relationships_target_capec_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )
  end
end
