defmodule Varsel.Repo.Migrations.AddOsvRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:osv_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :osv_id, :text, null: false
      add :osv_json, :map, null: false
      add :content_hash, :text, null: false
      add :modified_at, :utc_datetime_usec, null: false
      add :synced_at, :utc_datetime_usec, null: false
      add :withdrawn_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :cve_record_id,
          references(:cve_records,
            column: :id,
            name: "osv_records_cve_record_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:osv_records, [:cve_record_id],
             name: "osv_records_unique_cve_record_index"
           )

    create unique_index(:osv_records, [:osv_id], name: "osv_records_unique_osv_id_index")
  end

  def down do
    drop constraint(:osv_records, "osv_records_cve_record_id_fkey")

    drop_if_exists unique_index(:osv_records, [:osv_id], name: "osv_records_unique_osv_id_index")

    drop_if_exists unique_index(:osv_records, [:cve_record_id],
                     name: "osv_records_unique_cve_record_index"
                   )

    drop table(:osv_records)
  end
end
