defmodule CveManagement.Repo.Migrations.AddDomainModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :email, :text
      add :github_id, :text
      add :github_handle, :text
      add :name, :text
      add :role, :text
      add :public_gpg_key, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    create table(:git_hub_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :github_advisory_id, :text, null: false
      add :repository, :text, null: false
      add :title, :text, null: false
      add :body, :text, null: false
      add :severity, :text
      add :raw_payload, :map, null: false
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid
    end

    create table(:email_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :message_id, :text, null: false
      add :in_reply_to, :text
      add :from_email, :text, null: false
      add :from_name, :text
      add :subject, :text, null: false
      add :body_text, :text, null: false
      add :body_html, :text
      add :gpg_status, :text, null: false
      add :raw_headers, :map, null: false
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid
    end

    create table(:cve_reservations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :cve_id, :text, null: false
      add :status, :text, null: false
      add :reserved_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid
    end

    create table(:cve_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :cve_json, :map, null: false
      add :published_at, :utc_datetime
      add :last_synced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid
      add :state, :text, null: false, default: "publishing"
    end

    create unique_index(:cve_records, ["(cve_json->'cveMetadata'->>'cveId')"],
             name: "cve_records_unique_cve_id_index"
           )

    create table(:contact_gpg_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :armored_key, :text, null: false
      add :fingerprint, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:cases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:git_hub_reports) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "git_hub_reports_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:email_messages) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "email_messages_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cve_reservations) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "cve_reservations_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cve_records) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "cve_records_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cases) do
      add :title, :text
      add :severity_estimate, :text
      add :status, :text, null: false
      add :published_at, :utc_datetime
      add :approved_at, :utc_datetime
      add :rejected_at, :utc_datetime
      add :rejection_reason, :text
      add :reporter_email, :text
      add :reporter_name, :text
      add :sla_deadline_accept, :utc_datetime
      add :sla_deadline_feedback, :utc_datetime
      add :sla_deadline_publish, :utc_datetime
      add :publicly_exploited, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :approved_by_id,
          references(:users,
            column: :id,
            name: "cases_approved_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:case_threads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :channel, :text, null: false
      add :direction, :text, null: false
      add :body_raw, :text, null: false
      add :body_html, :text
      add :sender_email, :text
      add :sender_name, :text
      add :message_id, :text
      add :in_reply_to, :text
      add :gpg_signed, :boolean
      add :gpg_encrypted, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_threads_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:case_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_assignments_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "case_assignments_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:api_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_id, :uuid, null: false
      add :payload, :map, null: false
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "api_reports_case_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:ai_skill_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :skill, :text, null: false
      add :input_snapshot, :map, null: false
      add :output, :map
      add :model, :text, null: false
      add :status, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "ai_skill_runs_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:ai_skill_runs, "ai_skill_runs_case_id_fkey")

    drop table(:ai_skill_runs)

    drop constraint(:api_reports, "api_reports_case_id_fkey")

    drop table(:api_reports)

    drop constraint(:case_assignments, "case_assignments_case_id_fkey")

    drop constraint(:case_assignments, "case_assignments_user_id_fkey")

    drop table(:case_assignments)

    drop constraint(:case_threads, "case_threads_case_id_fkey")

    drop table(:case_threads)

    drop constraint(:cases, "cases_approved_by_id_fkey")

    alter table(:cases) do
      remove :approved_by_id
      remove :updated_at
      remove :inserted_at
      remove :publicly_exploited
      remove :sla_deadline_publish
      remove :sla_deadline_feedback
      remove :sla_deadline_accept
      remove :reporter_name
      remove :reporter_email
      remove :rejection_reason
      remove :rejected_at
      remove :approved_at
      remove :published_at
      remove :status
      remove :severity_estimate
      remove :title
    end

    drop constraint(:cve_records, "cve_records_case_id_fkey")

    alter table(:cve_records) do
      modify :case_id, :uuid
    end

    drop constraint(:cve_reservations, "cve_reservations_case_id_fkey")

    alter table(:cve_reservations) do
      modify :case_id, :uuid
    end

    drop constraint(:email_messages, "email_messages_case_id_fkey")

    alter table(:email_messages) do
      modify :case_id, :uuid
    end

    drop constraint(:git_hub_reports, "git_hub_reports_case_id_fkey")

    alter table(:git_hub_reports) do
      modify :case_id, :uuid
    end

    drop table(:cases)

    drop table(:contact_gpg_keys)

    drop_if_exists unique_index(:cve_records, ["(cve_json->'cveMetadata'->>'cveId')"],
                     name: "cve_records_unique_cve_id_index"
                   )

    drop table(:cve_records)

    drop table(:cve_reservations)

    drop table(:email_messages)

    drop table(:git_hub_reports)

    drop_if_exists unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :public_gpg_key
      remove :role
      remove :name
      remove :github_handle
      remove :github_id
      remove :email
    end
  end
end
