defmodule Varsel.Repo.Migrations.RemoveReportNotifiedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vulnerability_reports) do
      remove :notified_at
    end
  end

  def down do
    alter table(:vulnerability_reports) do
      add :notified_at, :utc_datetime
    end
  end
end
