defmodule Varsel.Repo.Migrations.DerivationCachedAtUsec do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:case_affected_packages) do
      modify :derivation_cached_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:case_affected_packages) do
      modify :derivation_cached_at, :utc_datetime
    end
  end
end
