defmodule Varsel.Repo.Migrations.AddGithubAdvisoryLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:case_github_advisory_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ghsa_id, :text, null: false
      add :owner, :text
      add :repo, :text
      add :html_url, :text, null: false
      add :state, :text, null: false, default: "unknown"
      add :title, :text
      add :cve_id, :text
      add :advisory, :map, null: false
      add :fetched_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_github_advisory_links_case_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:case_github_advisory_links, [:case_id],
             name: "case_github_advisory_links_unique_case_index"
           )

    create unique_index(:case_github_advisory_links, [:ghsa_id],
             name: "case_github_advisory_links_unique_ghsa_id_index"
           )

    create table(:case_github_advisory_links_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end
  end

  def down do
    drop table(:case_github_advisory_links_versions)

    drop constraint(:case_github_advisory_links, "case_github_advisory_links_case_id_fkey")

    drop_if_exists unique_index(:case_github_advisory_links, [:ghsa_id],
                     name: "case_github_advisory_links_unique_ghsa_id_index"
                   )

    drop_if_exists unique_index(:case_github_advisory_links, [:case_id],
                     name: "case_github_advisory_links_unique_case_index"
                   )

    drop table(:case_github_advisory_links)
  end
end
