defmodule Varsel.Repo.Migrations.AddNotificationEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notification_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :processed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "notification_events_case_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :vulnerability_report_id,
          references(:vulnerability_reports,
            column: :id,
            name: "notification_events_vulnerability_report_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :actor_id,
          references(:users,
            column: :id,
            name: "notification_events_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :recipient_id,
          references(:users,
            column: :id,
            name: "notification_events_recipient_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:notification_events, "notification_events_recipient_id_fkey")

    drop constraint(:notification_events, "notification_events_actor_id_fkey")

    drop constraint(:notification_events, "notification_events_vulnerability_report_id_fkey")

    drop constraint(:notification_events, "notification_events_case_id_fkey")

    drop table(:notification_events)
  end
end
