defmodule CveManagement.Repo.Migrations.AddCveRecordSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE FUNCTION cve_record_search_vector(cve_json jsonb)
    RETURNS tsvector
    LANGUAGE sql
    IMMUTABLE PARALLEL SAFE
    AS $$
      SELECT
        setweight(to_tsvector('english', coalesce(cve_json->'cveMetadata'->>'cveId', '')), 'A') ||
        setweight(to_tsvector('english', coalesce(cve_json->'containers'->'cna'->>'title', '')), 'A') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(d->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'descriptions', '[]'::jsonb)) AS d),
          ''
        )), 'B') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(
             coalesce(a->>'packageName', '') || ' ' ||
             coalesce(a->>'product', '') || ' ' ||
             coalesce(a->>'vendor', ''),
             ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'affected', '[]'::jsonb)) AS a),
          ''
        )), 'B') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(w->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'workarounds', '[]'::jsonb)) AS w),
          ''
        )), 'C') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(c->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'configurations', '[]'::jsonb)) AS c),
          ''
        )), 'C') ||
        setweight(to_tsvector('simple', regexp_replace(cve_json::text, '[^a-zA-Z0-9 ]', ' ', 'g')), 'D')
    $$
    """)

    execute("""
    ALTER TABLE cve_records ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (cve_record_search_vector(cve_json)) STORED
    """)

    execute("""
    CREATE INDEX cve_records_search_vector_gin ON cve_records USING GIN (search_vector)
    """)

    execute("""
    CREATE INDEX cve_records_affected_gin ON cve_records USING GIN ((cve_json->'containers'->'cna'->'affected'))
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS cve_records_affected_gin
    """)

    execute("""
    DROP INDEX IF EXISTS cve_records_search_vector_gin
    """)

    execute("""
    ALTER TABLE cve_records DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    DROP FUNCTION IF EXISTS cve_record_search_vector(jsonb)
    """)
  end
end
