# SPDX-FileCopyrightText: 2026 Erlang Ecosystem Foundation
#
# SPDX-License-Identifier: Apache-2.0

defmodule Varsel.Repo.Migrations.AddProseSections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:case_impacts) do
      add :description_md, :text
    end

    alter table(:cases) do
      add :technical_analysis_md, :text
      add :proof_of_concept_md, :text
    end
  end

  def down do
    alter table(:cases) do
      remove :proof_of_concept_md
      remove :technical_analysis_md
    end

    alter table(:case_impacts) do
      remove :description_md
    end
  end
end
