defmodule CveManagement.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text
      add :github_id, :text
      add :github_handle, :text
      add :name, :text
      add :role, :text
      add :public_gpg_key, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:git_hub_watched_targets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner, :text, null: false
      add :repo, :text
      add :synced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "git_hub_watched_targets_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:git_hub_watched_targets, [:user_id, :owner, :repo],
             name: "git_hub_watched_targets_unique_target_index"
           )

    create table(:git_hub_app_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :expires_at, :utc_datetime, null: false
      add :status, :text, null: false, default: "valid"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "git_hub_app_tokens_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :encrypted_access_token, :binary, null: false
      add :encrypted_refresh_token, :binary, null: false
    end

    create unique_index(:git_hub_app_tokens, [:user_id],
             name: "git_hub_app_tokens_unique_user_id_index"
           )

    create table(:git_hub_advisory_weaknesses, primary_key: false) do
      add :ghsa_id, :text, null: false, primary_key: true
      add :cwe_id, :bigint, null: false, primary_key: true
    end

    create table(:git_hub_advisories, primary_key: false) do
      add :ghsa_id, :text, null: false, primary_key: true
    end

    alter table(:git_hub_advisory_weaknesses) do
      modify :ghsa_id,
             references(:git_hub_advisories,
               column: :ghsa_id,
               name: "git_hub_advisory_weaknesses_ghsa_id_fkey",
               type: :text,
               prefix: "public"
             )
    end

    alter table(:git_hub_advisories) do
      add :cve_id, :text
      add :summary, :text, null: false
      add :description, :text
      add :severity, :text
      add :state, :text, null: false
      add :url, :text, null: false
      add :html_url, :text, null: false
      add :author, :map
      add :publisher, :map
      add :github_created_at, :utc_datetime
      add :github_updated_at, :utc_datetime
      add :github_published_at, :utc_datetime
      add :github_closed_at, :utc_datetime
      add :github_withdrawn_at, :utc_datetime
      add :vulnerabilities, {:array, :map}
      add :cvss_severities, :map
      add :identifiers, {:array, :map}
      add :credits, {:array, :map}
      add :credits_detailed, {:array, :map}
      add :collaborating_users, {:array, :map}
      add :collaborating_teams, {:array, :map}
      add :submission, :map
      add :private_fork, :map
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :fetched_by_user_id,
          references(:users,
            column: :id,
            name: "git_hub_advisories_fetched_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :case_id, :uuid
    end

    create table(:email_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :message_id, :text, null: false
      add :in_reply_to, :text
      add :from_email, :text, null: false
      add :from_name, :text
      add :subject, :text, null: false
      add :body_text, :text, null: false
      add :body_html, :text
      add :gpg_status, :text, null: false
      add :raw_headers, :map, null: false
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid
    end

    create table(:cwe_weaknesses, primary_key: false) do
      add :cwe_id, :bigint, null: false, primary_key: true
    end

    alter table(:git_hub_advisory_weaknesses) do
      modify :cwe_id,
             references(:cwe_weaknesses,
               column: :cwe_id,
               name: "git_hub_advisory_weaknesses_cwe_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:cwe_weaknesses) do
      add :name, :text, null: false
      add :abstraction, :text, null: false
      add :status, :text, null: false
      add :description, :text, null: false
      add :extended_description, :text
      add :potential_mitigations, :text
      add :common_consequences, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:cwe_weakness_relationships, primary_key: false) do
      add :source_cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "cwe_weakness_relationships_source_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :target_cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "cwe_weakness_relationships_target_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :nature, :text, null: false, primary_key: true
      add :view_id, :bigint, null: false, primary_key: true
      add :ordinal, :text
    end

    create table(:cwe_metadata, primary_key: false) do
      add :singleton_key, :text, null: false, default: "singleton", primary_key: true
      add :last_modified, :text
      add :last_synced_at, :utc_datetime
    end

    create table(:cve_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reservation_json, :map
      add :cve_json, :map
      add :last_synced_at, :utc_datetime
      add :rejected_at, :utc_datetime
      add :rejection_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid
      add :state, :text, null: false, default: "reserved"
    end

    create unique_index(
             :cve_records,
             ["(coalesce(cve_json->'cveMetadata'->>'cveId', reservation_json->>'cve_id'))"],
             name: "cve_records_unique_cve_id_index"
           )

    create table(:contact_gpg_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :armored_key, :text, null: false
      add :fingerprint, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:cases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:git_hub_advisories) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "git_hub_advisories_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:email_messages) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "email_messages_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cve_records) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "cve_records_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cases) do
      add :title, :text
      add :severity_estimate, :text
      add :status, :text, null: false
      add :published_at, :utc_datetime
      add :approved_at, :utc_datetime
      add :rejected_at, :utc_datetime
      add :rejection_reason, :text
      add :reporter_email, :text
      add :reporter_name, :text
      add :sla_deadline_accept, :utc_datetime
      add :sla_deadline_feedback, :utc_datetime
      add :sla_deadline_publish, :utc_datetime
      add :publicly_exploited, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :approved_by_id,
          references(:users,
            column: :id,
            name: "cases_approved_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:case_threads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :channel, :text, null: false
      add :direction, :text, null: false
      add :body_raw, :text, null: false
      add :body_html, :text
      add :sender_email, :text
      add :sender_name, :text
      add :message_id, :text
      add :in_reply_to, :text
      add :gpg_signed, :boolean
      add :gpg_encrypted, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_threads_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:case_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_assignments_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "case_assignments_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:capec_metadata, primary_key: false) do
      add :singleton_key, :text, null: false, default: "singleton", primary_key: true
      add :last_modified, :text
      add :last_synced_at, :utc_datetime
    end

    create table(:capec_attack_patterns, primary_key: false) do
      add :capec_id, :bigint, null: false, primary_key: true
      add :name, :text, null: false
      add :abstraction, :text, null: false
      add :status, :text, null: false
      add :description, :text
      add :extended_description, :text
      add :likelihood_of_attack, :text
      add :typical_severity, :text
      add :prerequisites, :text
      add :mitigations, :text
      add :consequences, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:capec_attack_pattern_weaknesses, primary_key: false) do
      add :capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "capec_attack_pattern_weaknesses_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "capec_attack_pattern_weaknesses_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create table(:capec_attack_pattern_relationships, primary_key: false) do
      add :source_capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "capec_attack_pattern_relationships_source_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :target_capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "capec_attack_pattern_relationships_target_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :nature, :text, null: false, primary_key: true
    end

    create table(:api_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_id, :uuid, null: false
      add :payload, :map, null: false
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "api_reports_case_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:ai_skill_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :skill, :text, null: false
      add :input_snapshot, :map, null: false
      add :output, :map
      add :model, :text, null: false
      add :status, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "ai_skill_runs_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    execute(
      "ALTER TABLE capec_attack_pattern_relationships ALTER CONSTRAINT capec_attack_pattern_relationships_target_capec_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute("""
    ALTER TABLE capec_attack_patterns
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(extended_description, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(prerequisites, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(mitigations, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(consequences, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX capec_attack_patterns_search_vector_gin ON capec_attack_patterns USING GIN (search_vector)
    """)

    execute("""
    CREATE FUNCTION cve_record_search_vector(cve_json jsonb)
    RETURNS tsvector
    LANGUAGE sql
    IMMUTABLE PARALLEL SAFE
    AS $$
      SELECT
        setweight(to_tsvector('english', coalesce(cve_json->'cveMetadata'->>'cveId', '')), 'A') ||
        setweight(to_tsvector('english', coalesce(cve_json->'containers'->'cna'->>'title', '')), 'A') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(d->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'descriptions', '[]'::jsonb)) AS d),
          ''
        )), 'B') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(
             coalesce(a->>'packageName', '') || ' ' ||
             coalesce(a->>'product', '') || ' ' ||
             coalesce(a->>'vendor', ''),
             ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'affected', '[]'::jsonb)) AS a),
          ''
        )), 'B') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(w->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'workarounds', '[]'::jsonb)) AS w),
          ''
        )), 'C') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(c->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'configurations', '[]'::jsonb)) AS c),
          ''
        )), 'C') ||
        setweight(to_tsvector('simple', regexp_replace(cve_json::text, '[^a-zA-Z0-9 ]', ' ', 'g')), 'D')
    $$
    """)

    execute("""
    ALTER TABLE cve_records ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (cve_record_search_vector(coalesce(cve_json, '{}'::jsonb))) STORED
    """)

    execute("""
    CREATE INDEX cve_records_search_vector_gin ON cve_records USING GIN (search_vector)
    """)

    execute("""
    CREATE INDEX cve_records_affected_gin ON cve_records USING GIN ((cve_json->'containers'->'cna'->'affected'))
    """)

    execute(
      "ALTER TABLE cwe_weakness_relationships ALTER CONSTRAINT cwe_weakness_relationships_target_cwe_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute("""
    ALTER TABLE cwe_weaknesses
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(extended_description, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(potential_mitigations, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(common_consequences, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX cwe_weaknesses_search_vector_gin ON cwe_weaknesses USING GIN (search_vector)
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS cwe_weaknesses_search_vector_gin
    """)

    execute("""
    ALTER TABLE cwe_weaknesses DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    DROP INDEX IF EXISTS cve_records_affected_gin
    """)

    execute("""
    DROP INDEX IF EXISTS cve_records_search_vector_gin
    """)

    execute("""
    ALTER TABLE cve_records DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    DROP FUNCTION IF EXISTS cve_record_search_vector(jsonb)
    """)

    execute("""
    DROP INDEX IF EXISTS capec_attack_patterns_search_vector_gin
    """)

    execute("""
    ALTER TABLE capec_attack_patterns DROP COLUMN IF EXISTS search_vector
    """)

    drop constraint(:ai_skill_runs, "ai_skill_runs_case_id_fkey")

    drop table(:ai_skill_runs)

    drop constraint(:api_reports, "api_reports_case_id_fkey")

    drop table(:api_reports)

    drop constraint(
           :capec_attack_pattern_relationships,
           "capec_attack_pattern_relationships_source_capec_id_fkey"
         )

    drop constraint(
           :capec_attack_pattern_relationships,
           "capec_attack_pattern_relationships_target_capec_id_fkey"
         )

    drop table(:capec_attack_pattern_relationships)

    drop constraint(
           :capec_attack_pattern_weaknesses,
           "capec_attack_pattern_weaknesses_capec_id_fkey"
         )

    drop constraint(
           :capec_attack_pattern_weaknesses,
           "capec_attack_pattern_weaknesses_cwe_id_fkey"
         )

    drop table(:capec_attack_pattern_weaknesses)

    drop table(:capec_attack_patterns)

    drop table(:capec_metadata)

    drop constraint(:case_assignments, "case_assignments_case_id_fkey")

    drop constraint(:case_assignments, "case_assignments_user_id_fkey")

    drop table(:case_assignments)

    drop constraint(:case_threads, "case_threads_case_id_fkey")

    drop table(:case_threads)

    drop constraint(:cases, "cases_approved_by_id_fkey")

    alter table(:cases) do
      remove :approved_by_id
      remove :updated_at
      remove :inserted_at
      remove :publicly_exploited
      remove :sla_deadline_publish
      remove :sla_deadline_feedback
      remove :sla_deadline_accept
      remove :reporter_name
      remove :reporter_email
      remove :rejection_reason
      remove :rejected_at
      remove :approved_at
      remove :published_at
      remove :status
      remove :severity_estimate
      remove :title
    end

    drop constraint(:cve_records, "cve_records_case_id_fkey")

    alter table(:cve_records) do
      modify :case_id, :uuid
    end

    drop constraint(:email_messages, "email_messages_case_id_fkey")

    alter table(:email_messages) do
      modify :case_id, :uuid
    end

    drop constraint(:git_hub_advisories, "git_hub_advisories_case_id_fkey")

    alter table(:git_hub_advisories) do
      modify :case_id, :uuid
    end

    drop table(:cases)

    drop table(:contact_gpg_keys)

    drop_if_exists unique_index(
                     :cve_records,
                     [
                       "(coalesce(cve_json->'cveMetadata'->>'cveId', reservation_json->>'cve_id'))"
                     ],
                     name: "cve_records_unique_cve_id_index"
                   )

    drop table(:cve_records)

    drop table(:cwe_metadata)

    drop constraint(:cwe_weakness_relationships, "cwe_weakness_relationships_source_cwe_id_fkey")

    drop constraint(:cwe_weakness_relationships, "cwe_weakness_relationships_target_cwe_id_fkey")

    drop table(:cwe_weakness_relationships)

    alter table(:cwe_weaknesses) do
      remove :updated_at
      remove :inserted_at
      remove :common_consequences
      remove :potential_mitigations
      remove :extended_description
      remove :description
      remove :status
      remove :abstraction
      remove :name
    end

    drop constraint(:git_hub_advisory_weaknesses, "git_hub_advisory_weaknesses_cwe_id_fkey")

    alter table(:git_hub_advisory_weaknesses) do
      modify :cwe_id, :bigint
    end

    drop table(:cwe_weaknesses)

    drop table(:email_messages)

    drop constraint(:git_hub_advisories, "git_hub_advisories_fetched_by_user_id_fkey")

    alter table(:git_hub_advisories) do
      remove :case_id
      remove :fetched_by_user_id
      remove :updated_at
      remove :inserted_at
      remove :processed_at
      remove :private_fork
      remove :submission
      remove :collaborating_teams
      remove :collaborating_users
      remove :credits_detailed
      remove :credits
      remove :identifiers
      remove :cvss_severities
      remove :vulnerabilities
      remove :github_withdrawn_at
      remove :github_closed_at
      remove :github_published_at
      remove :github_updated_at
      remove :github_created_at
      remove :publisher
      remove :author
      remove :html_url
      remove :url
      remove :state
      remove :severity
      remove :description
      remove :summary
      remove :cve_id
    end

    drop constraint(:git_hub_advisory_weaknesses, "git_hub_advisory_weaknesses_ghsa_id_fkey")

    alter table(:git_hub_advisory_weaknesses) do
      modify :ghsa_id, :text
    end

    drop table(:git_hub_advisories)

    drop table(:git_hub_advisory_weaknesses)

    drop constraint(:git_hub_app_tokens, "git_hub_app_tokens_user_id_fkey")

    drop_if_exists unique_index(:git_hub_app_tokens, [:user_id],
                     name: "git_hub_app_tokens_unique_user_id_index"
                   )

    drop table(:git_hub_app_tokens)

    drop constraint(:git_hub_watched_targets, "git_hub_watched_targets_user_id_fkey")

    drop_if_exists unique_index(:git_hub_watched_targets, [:user_id, :owner, :repo],
                     name: "git_hub_watched_targets_unique_target_index"
                   )

    drop table(:git_hub_watched_targets)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    drop table(:users)

    execute(
      "ALTER TABLE cwe_weakness_relationships ALTER CONSTRAINT cwe_weakness_relationships_target_cwe_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute(
      "ALTER TABLE capec_attack_pattern_relationships ALTER CONSTRAINT capec_attack_pattern_relationships_target_capec_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )
  end
end
