defmodule CveManagement.Repo.Migrations.FixCveReservationJsonFieldNames do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:cve_reservations, ["(reservation_json->>'cveId')"],
                     name: "cve_reservations_unique_cve_id_index"
                   )

    create unique_index(:cve_reservations, ["(reservation_json->>'cve_id')"],
             name: "cve_reservations_unique_cve_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cve_reservations, ["(reservation_json->>'cve_id')"],
                     name: "cve_reservations_unique_cve_id_index"
                   )

    create unique_index(:cve_reservations, ["(reservation_json->>'cveId')"],
             name: "cve_reservations_unique_cve_id_index"
           )
  end
end
