defmodule Varsel.Repo.Migrations.AddCveRecordCweCapecIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE FUNCTION cve_record_cwe_ids(document jsonb)
    RETURNS text[]
    LANGUAGE sql
    IMMUTABLE
    PARALLEL SAFE
    STRICT
    AS $$
      SELECT COALESCE(
        array_agg(DISTINCT cwe_id ORDER BY cwe_id),
        ARRAY[]::text[]
      )
      FROM jsonb_array_elements(
        COALESCE(
          document #> '{containers,cna,problemTypes}',
          '[]'::jsonb
        )
      ) AS problem_type
      CROSS JOIN LATERAL jsonb_array_elements(
        COALESCE(
          problem_type -> 'descriptions',
          '[]'::jsonb
        )
      ) AS description
      CROSS JOIN LATERAL (
        SELECT description ->> 'cweId' AS cwe_id
      ) AS extracted
      WHERE cwe_id IS NOT NULL;
    $$;
    """)

    execute("""
    CREATE INDEX cve_records_cwe_ids ON cve_records USING GIN (cve_record_cwe_ids(cve_json))
    """)

    execute("""
    CREATE FUNCTION cve_record_capec_ids(document jsonb)
    RETURNS text[]
    LANGUAGE sql
    IMMUTABLE
    PARALLEL SAFE
    STRICT
    AS $$
      SELECT COALESCE(
        array_agg(DISTINCT capec_id ORDER BY capec_id),
        ARRAY[]::text[]
      )
      FROM jsonb_array_elements(
        COALESCE(
          document #> '{containers,cna,impacts}',
          '[]'::jsonb
        )
      ) AS impact
      CROSS JOIN LATERAL (
        SELECT impact ->> 'capecId' AS capec_id
      ) AS extracted
      WHERE capec_id IS NOT NULL;
    $$;
    """)

    execute("""
    CREATE INDEX cve_records_capec_ids ON cve_records USING GIN (cve_record_capec_ids(cve_json))
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS cve_records_capec_ids
    """)

    execute("""
    DROP FUNCTION IF EXISTS cve_record_capec_ids(jsonb)
    """)

    execute("""
    DROP INDEX IF EXISTS cve_records_cwe_ids
    """)

    execute("""
    DROP FUNCTION IF EXISTS cve_record_cwe_ids(jsonb)
    """)
  end
end
