defmodule Varsel.Repo.Migrations.AddCveAssignedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases) do
      add :cve_assigned_at, :utc_datetime
    end
  end

  def down do
    alter table(:cases) do
      remove :cve_assigned_at
    end
  end
end
