defmodule Varsel.Repo.Migrations.AllowUnreleasedIntro do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:case_affected_packages) do
      add :allow_unreleased_intro, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:case_affected_packages) do
      remove :allow_unreleased_intro
    end
  end
end
