defmodule Varsel.Repo.Migrations.AddCimdToOauthClients do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:oauth_clients) do
      add :cimd_url, :text
    end

    create unique_index(:oauth_clients, [:cimd_url], name: "oauth_clients_by_cimd_url_index")
  end

  def down do
    drop_if_exists unique_index(:oauth_clients, [:cimd_url],
                     name: "oauth_clients_by_cimd_url_index"
                   )

    alter table(:oauth_clients) do
      remove :cimd_url
    end
  end
end
