# SPDX-FileCopyrightText: 2026 Erlang Ecosystem Foundation
#
# SPDX-License-Identifier: Apache-2.0

defmodule Varsel.Repo.Migrations.AddCreditHandlesAndPreferredCredit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:case_credits) do
      add :handles, {:array, :map}, null: false, default: []
    end

    alter table(:users) do
      add :credit_name, :text
      add :credit_organization, :text
    end
  end

  def down do
    alter table(:users) do
      remove :credit_organization
      remove :credit_name
    end

    alter table(:case_credits) do
      remove :handles
    end
  end
end
