defmodule CveManagement.Repo.Migrations.AddCweDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cwe_weaknesses, primary_key: false) do
      add :cwe_id, :bigint, null: false, primary_key: true
      add :name, :text, null: false
      add :abstraction, :text, null: false
      add :status, :text, null: false
      add :description, :text, null: false
      add :extended_description, :text
      add :related_weaknesses, {:array, :map}, null: false, default: []
      add :potential_mitigations, :text
      add :common_consequences, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:cwe_metadata, primary_key: false) do
      add :singleton_key, :text, null: false, default: "singleton", primary_key: true
      add :last_modified, :text
      add :last_synced_at, :utc_datetime
    end

    execute("""
    ALTER TABLE cwe_weaknesses
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(extended_description, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(potential_mitigations, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(common_consequences, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX cwe_weaknesses_search_vector_gin ON cwe_weaknesses USING GIN (search_vector)
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS cwe_weaknesses_search_vector_gin
    """)

    execute("""
    ALTER TABLE cwe_weaknesses DROP COLUMN IF EXISTS search_vector
    """)

    drop table(:cwe_metadata)

    drop table(:cwe_weaknesses)
  end
end
