defmodule Varsel.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:case_assignments_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:case_proposals_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :state, :text, null: false, default: "open"
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:vulnerability_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :report_json, :map, null: false
      add :summary, :text, null: false
      add :triage_notes, :text
      add :state, :text, null: false, default: "submitted"
      add :notified_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :reporter_id, :uuid, null: false
      add :case_id, :uuid
    end

    create table(:case_version_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event, :text, null: false
      add :commit_sha, :text
      add :version, :text
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
      add :affected_package_id, :uuid, null: false
      add :package_channel_id, :uuid
    end

    create table(:cwe_weaknesses, primary_key: false) do
      add :cwe_id, :bigint, null: false, primary_key: true
      add :name, :text, null: false
      add :abstraction, :text, null: false
      add :status, :text, null: false
      add :description, :text, null: false
      add :extended_description, :text
      add :potential_mitigations, :text
      add :common_consequences, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:case_credits_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:cve_records_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :state, :text, null: false, default: "reserved"
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:case_affected_packages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :vendor, :text, null: false
      add :product, :text, null: false
      add :repo_url, :text
      add :cpe, :text
      add :default_status, :text, null: false, default: "unaffected"
      add :modules, {:array, :text}, null: false, default: []
      add :program_files, {:array, :text}, null: false, default: []
      add :program_routines, {:array, :text}, null: false, default: []
      add :platforms, {:array, :text}, null: false, default: []
      add :allow_unreleased_fix, :boolean, null: false, default: false
      add :position, :bigint, null: false, default: 0
      add :derivation_cache, :map
      add :derivation_cached_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
    end

    create table(:case_impacts_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:case_weaknesses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
      add :cwe_id, :bigint, null: false
    end

    create unique_index(:case_weaknesses, [:case_id, :cwe_id],
             name: "case_weaknesses_unique_case_cwe_index"
           )

    create table(:capec_metadata, primary_key: false) do
      add :singleton_key, :text, null: false, default: "singleton", primary_key: true
      add :last_modified, :text
      add :last_synced_at, :utc_datetime
    end

    create table(:case_affected_packages_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:cwe_metadata, primary_key: false) do
      add :singleton_key, :text, null: false, default: "singleton", primary_key: true
      add :last_modified, :text
      add :last_synced_at, :utc_datetime
    end

    create table(:case_package_channels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :channel_type, :text, null: false
      add :package_name, :text
      add :registry_url, :text
      add :tag_suffixes, {:array, :text}, null: false, default: []
      add :versions_override, {:array, :map}
      add :entry_override, :map
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
      add :affected_package_id, :uuid, null: false
    end

    create unique_index(
             :case_package_channels,
             [:affected_package_id, :channel_type, :package_name],
             name: "case_package_channels_unique_channel_index"
           )

    create table(:user_identities, primary_key: false) do
      add :refresh_token, :text
      add :access_token_expires_at, :utc_datetime_usec
      add :access_token, :text
      add :uid, :text, null: false
      add :strategy, :text, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid
    end

    create unique_index(:user_identities, [:strategy, :uid],
             name: "user_identities_unique_on_strategy_and_uid_index"
           )

    create table(:capec_attack_pattern_relationships, primary_key: false) do
      add :source_capec_id, :bigint, null: false, primary_key: true
      add :target_capec_id, :bigint, null: false, primary_key: true
      add :nature, :text, null: false, primary_key: true
    end

    create table(:case_version_events_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:users_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:case_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create unique_index(:case_assignments, [:case_id, :user_id],
             name: "case_assignments_unique_case_user_index"
           )

    create table(:case_proposals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :target, :text, null: false
      add :target_id, :uuid
      add :operation, :text, null: false
      add :field_name, :text
      add :proposed_value, :map
      add :reasoning, :text
      add :state, :text, null: false, default: "open"
      add :resolution_note, :text
      add :resolved_at, :utc_datetime_usec
      add :applied_target_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
      add :author_id, :uuid, null: false
      add :resolved_by_id, :uuid
      add :parent_proposal_id, :uuid
    end

    create index(:case_proposals, [:target, :target_id, :field_name], where: "state = 'open'")

    create index(:case_proposals, [:case_id, :state])

    create table(:cases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:case_version_events) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "case_version_events_case_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :affected_package_id,
             references(:case_affected_packages,
               column: :id,
               name: "case_version_events_affected_package_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :package_channel_id,
             references(:case_package_channels,
               column: :id,
               name: "case_version_events_package_channel_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:case_affected_packages) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "case_affected_packages_case_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:case_weaknesses) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "case_weaknesses_case_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :cwe_id,
             references(:cwe_weaknesses,
               column: :cwe_id,
               name: "case_weaknesses_cwe_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:case_package_channels) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "case_package_channels_case_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :affected_package_id,
             references(:case_affected_packages,
               column: :id,
               name: "case_package_channels_affected_package_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:case_assignments) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "case_assignments_case_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:case_proposals) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "case_proposals_case_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:cases) do
      add :state, :text, null: false, default: "draft"
      add :title, :text
      add :description_md, :text
      add :workarounds_md, :text
      add :configurations_md, :text
      add :solutions_md, :text
      add :discovery, :text, null: false, default: "unknown"
      add :cvss_v4, :map
      add :date_public, :utc_datetime
      add :timeline, {:array, :map}, null: false, default: []
      add :cna_override, :map
      add :internal_notes, :text
      add :closed_reason, :text
      add :published_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :cve_record_id, :uuid
    end

    create unique_index(:cases, [:cve_record_id], name: "cases_unique_cve_record_index")

    create table(:capec_attack_pattern_weaknesses, primary_key: false) do
      add :capec_id, :bigint, null: false, primary_key: true
      add :cwe_id, :bigint, null: false, primary_key: true
    end

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:api_keys_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:case_comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_comments_case_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :author_id, :uuid, null: false
      add :proposal_id, :uuid
    end

    create index(:case_comments, [:case_id, :inserted_at])

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:case_assignments_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_assignments_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:case_proposals_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_proposals_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:vulnerability_reports) do
      modify :reporter_id,
             references(:users,
               column: :id,
               name: "vulnerability_reports_reporter_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :case_id,
             references(:cases,
               column: :id,
               name: "vulnerability_reports_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:case_credits_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_credits_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:case_impacts_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_impacts_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:case_affected_packages_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_affected_packages_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:user_identities) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "user_identities_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:case_version_events_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_version_events_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:users_versions) do
      modify :version_source_id,
             references(:users,
               column: :id,
               name: "users_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "users_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:case_assignments) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "case_assignments_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:case_proposals) do
      modify :author_id,
             references(:users,
               column: :id,
               name: "case_proposals_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :resolved_by_id,
             references(:users,
               column: :id,
               name: "case_proposals_resolved_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :parent_proposal_id,
             references(:case_proposals,
               column: :id,
               name: "case_proposals_parent_proposal_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:api_keys_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "api_keys_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:case_comments) do
      modify :author_id,
             references(:users,
               column: :id,
               name: "case_comments_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :proposal_id,
             references(:case_proposals,
               column: :id,
               name: "case_comments_proposal_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:users) do
      add :email, :text
      add :github_id, :text
      add :github_handle, :text
      add :name, :text
      add :role, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    create table(:case_references_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "case_references_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:cve_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:cve_records_versions) do
      modify :version_source_id,
             references(:cve_records,
               column: :id,
               name: "cve_records_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "cve_records_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    alter table(:cases) do
      modify :cve_record_id,
             references(:cve_records,
               column: :id,
               name: "cases_cve_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:cve_records) do
      add :reservation_json, :map
      add :cve_json, :map
      add :last_synced_at, :utc_datetime
      add :rejected_at, :utc_datetime
      add :rejection_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "reserved"
    end

    create unique_index(
             :cve_records,
             ["(coalesce(cve_json->'cveMetadata'->>'cveId', reservation_json->>'cve_id'))"],
             name: "cve_records_unique_cve_id_index"
           )

    create table(:tokens_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :text, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "tokens_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:capec_attack_patterns, primary_key: false) do
      add :capec_id, :bigint, null: false, primary_key: true
    end

    alter table(:capec_attack_pattern_relationships) do
      modify :source_capec_id,
             references(:capec_attack_patterns,
               column: :capec_id,
               name: "capec_attack_pattern_relationships_source_capec_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :target_capec_id,
             references(:capec_attack_patterns,
               column: :capec_id,
               name: "capec_attack_pattern_relationships_target_capec_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:capec_attack_pattern_weaknesses) do
      modify :capec_id,
             references(:capec_attack_patterns,
               column: :capec_id,
               name: "capec_attack_pattern_weaknesses_capec_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :cwe_id,
             references(:cwe_weaknesses,
               column: :cwe_id,
               name: "capec_attack_pattern_weaknesses_cwe_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:capec_attack_patterns) do
      add :name, :text, null: false
      add :abstraction, :text, null: false
      add :status, :text, null: false
      add :description, :text
      add :extended_description, :text
      add :likelihood_of_attack, :text
      add :typical_severity, :text
      add :prerequisites, :text
      add :mitigations, :text
      add :consequences, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:osv_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :osv_id, :text, null: false
      add :osv_json, :map, null: false
      add :content_hash, :text, null: false
      add :modified_at, :utc_datetime_usec, null: false
      add :synced_at, :utc_datetime_usec, null: false
      add :withdrawn_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :cve_record_id,
          references(:cve_records,
            column: :id,
            name: "osv_records_cve_record_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:osv_records, [:cve_record_id],
             name: "osv_records_unique_cve_record_index"
           )

    create unique_index(:osv_records, [:osv_id], name: "osv_records_unique_osv_id_index")

    create table(:case_comments_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "case_comments_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:case_package_channels_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "case_package_channels_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:user_identities_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_identities_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:case_impacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_impacts_case_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :capec_id,
          references(:capec_attack_patterns,
            column: :capec_id,
            name: "case_impacts_capec_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:case_impacts, [:case_id, :capec_id],
             name: "case_impacts_unique_case_capec_index"
           )

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    create table(:case_weaknesses_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "case_weaknesses_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:cases_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :state, :text, null: false, default: "draft"
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "cases_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:case_references, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :url, :text, null: false
      add :tags, {:array, :text}, null: false, default: []
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_references_case_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:case_references, [:case_id, :url],
             name: "case_references_unique_case_url_index"
           )

    create table(:cwe_weakness_relationships, primary_key: false) do
      add :source_cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "cwe_weakness_relationships_source_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false

      add :target_cwe_id,
          references(:cwe_weaknesses,
            column: :cwe_id,
            name: "cwe_weakness_relationships_target_cwe_id_fkey",
            type: :bigint,
            prefix: "public"
          ), primary_key: true, null: false

      add :nature, :text, null: false, primary_key: true
      add :view_id, :bigint, null: false, primary_key: true
      add :ordinal, :text
    end

    create table(:case_credits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :organization, :text
      add :credit_type, :text, null: false, default: "finder"
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_credits_case_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "case_credits_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:vulnerability_reports_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :state, :text, null: false, default: "submitted"

      add :version_source_id,
          references(:vulnerability_reports,
            column: :id,
            name: "vulnerability_reports_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "vulnerability_reports_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    execute(
      "ALTER TABLE cwe_weakness_relationships ALTER CONSTRAINT cwe_weakness_relationships_target_cwe_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute("""
    ALTER TABLE capec_attack_patterns
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(extended_description, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(prerequisites, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(mitigations, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(consequences, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX capec_attack_patterns_search_vector_gin ON capec_attack_patterns USING GIN (search_vector)
    """)

    execute("""
    CREATE FUNCTION cve_record_search_vector(cve_json jsonb)
    RETURNS tsvector
    LANGUAGE sql
    IMMUTABLE PARALLEL SAFE
    AS $$
      SELECT
        setweight(to_tsvector('english', coalesce(cve_json->'cveMetadata'->>'cveId', '')), 'A') ||
        setweight(to_tsvector('english', coalesce(cve_json->'containers'->'cna'->>'title', '')), 'A') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(d->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'descriptions', '[]'::jsonb)) AS d),
          ''
        )), 'B') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(
             coalesce(a->>'packageName', '') || ' ' ||
             coalesce(a->>'product', '') || ' ' ||
             coalesce(a->>'vendor', ''),
             ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'affected', '[]'::jsonb)) AS a),
          ''
        )), 'B') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(w->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'workarounds', '[]'::jsonb)) AS w),
          ''
        )), 'C') ||
        setweight(to_tsvector('english', coalesce(
          (SELECT string_agg(c->>'value', ' ')
           FROM jsonb_array_elements(coalesce(cve_json->'containers'->'cna'->'configurations', '[]'::jsonb)) AS c),
          ''
        )), 'C') ||
        setweight(to_tsvector('simple', regexp_replace(cve_json::text, '[^a-zA-Z0-9 ]', ' ', 'g')), 'D')
    $$
    """)

    execute("""
    ALTER TABLE cve_records ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (cve_record_search_vector(coalesce(cve_json, '{}'::jsonb))) STORED
    """)

    execute("""
    CREATE INDEX cve_records_search_vector_gin ON cve_records USING GIN (search_vector)
    """)

    execute("""
    CREATE INDEX cve_records_affected_gin ON cve_records USING GIN ((cve_json->'containers'->'cna'->'affected'))
    """)

    execute(
      "ALTER TABLE capec_attack_pattern_relationships ALTER CONSTRAINT capec_attack_pattern_relationships_target_capec_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute("""
    ALTER TABLE cwe_weaknesses
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(extended_description, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(potential_mitigations, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(common_consequences, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX cwe_weaknesses_search_vector_gin ON cwe_weaknesses USING GIN (search_vector)
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS cwe_weaknesses_search_vector_gin
    """)

    execute("""
    ALTER TABLE cwe_weaknesses DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    DROP INDEX IF EXISTS cve_records_affected_gin
    """)

    execute("""
    DROP INDEX IF EXISTS cve_records_search_vector_gin
    """)

    execute("""
    ALTER TABLE cve_records DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    DROP FUNCTION IF EXISTS cve_record_search_vector(jsonb)
    """)

    execute("""
    DROP INDEX IF EXISTS capec_attack_patterns_search_vector_gin
    """)

    execute("""
    ALTER TABLE capec_attack_patterns DROP COLUMN IF EXISTS search_vector
    """)

    drop constraint(
           :vulnerability_reports_versions,
           "vulnerability_reports_versions_version_source_id_fkey"
         )

    drop constraint(
           :vulnerability_reports_versions,
           "vulnerability_reports_versions_user_id_fkey"
         )

    drop table(:vulnerability_reports_versions)

    drop constraint(:case_credits, "case_credits_case_id_fkey")

    drop constraint(:case_credits, "case_credits_user_id_fkey")

    drop table(:case_credits)

    drop constraint(:cwe_weakness_relationships, "cwe_weakness_relationships_source_cwe_id_fkey")

    drop constraint(:cwe_weakness_relationships, "cwe_weakness_relationships_target_cwe_id_fkey")

    drop table(:cwe_weakness_relationships)

    drop constraint(:case_references, "case_references_case_id_fkey")

    drop_if_exists unique_index(:case_references, [:case_id, :url],
                     name: "case_references_unique_case_url_index"
                   )

    drop table(:case_references)

    drop constraint(:cases_versions, "cases_versions_user_id_fkey")

    drop table(:cases_versions)

    drop constraint(:case_weaknesses_versions, "case_weaknesses_versions_user_id_fkey")

    drop table(:case_weaknesses_versions)

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop table(:api_keys)

    drop constraint(:case_impacts, "case_impacts_case_id_fkey")

    drop constraint(:case_impacts, "case_impacts_capec_id_fkey")

    drop_if_exists unique_index(:case_impacts, [:case_id, :capec_id],
                     name: "case_impacts_unique_case_capec_index"
                   )

    drop table(:case_impacts)

    drop constraint(:user_identities_versions, "user_identities_versions_user_id_fkey")

    drop table(:user_identities_versions)

    drop constraint(
           :case_package_channels_versions,
           "case_package_channels_versions_user_id_fkey"
         )

    drop table(:case_package_channels_versions)

    drop constraint(:case_comments_versions, "case_comments_versions_user_id_fkey")

    drop table(:case_comments_versions)

    drop constraint(:osv_records, "osv_records_cve_record_id_fkey")

    drop_if_exists unique_index(:osv_records, [:osv_id], name: "osv_records_unique_osv_id_index")

    drop_if_exists unique_index(:osv_records, [:cve_record_id],
                     name: "osv_records_unique_cve_record_index"
                   )

    drop table(:osv_records)

    alter table(:capec_attack_patterns) do
      remove :updated_at
      remove :inserted_at
      remove :consequences
      remove :mitigations
      remove :prerequisites
      remove :typical_severity
      remove :likelihood_of_attack
      remove :extended_description
      remove :description
      remove :status
      remove :abstraction
      remove :name
    end

    drop constraint(
           :capec_attack_pattern_weaknesses,
           "capec_attack_pattern_weaknesses_capec_id_fkey"
         )

    drop constraint(
           :capec_attack_pattern_weaknesses,
           "capec_attack_pattern_weaknesses_cwe_id_fkey"
         )

    alter table(:capec_attack_pattern_weaknesses) do
      modify :cwe_id, :bigint
      modify :capec_id, :bigint
    end

    drop constraint(
           :capec_attack_pattern_relationships,
           "capec_attack_pattern_relationships_source_capec_id_fkey"
         )

    drop constraint(
           :capec_attack_pattern_relationships,
           "capec_attack_pattern_relationships_target_capec_id_fkey"
         )

    alter table(:capec_attack_pattern_relationships) do
      modify :target_capec_id, :bigint
      modify :source_capec_id, :bigint
    end

    drop table(:capec_attack_patterns)

    drop constraint(:tokens_versions, "tokens_versions_user_id_fkey")

    drop table(:tokens_versions)

    drop_if_exists unique_index(
                     :cve_records,
                     [
                       "(coalesce(cve_json->'cveMetadata'->>'cveId', reservation_json->>'cve_id'))"
                     ],
                     name: "cve_records_unique_cve_id_index"
                   )

    alter table(:cve_records) do
      remove :state
      remove :updated_at
      remove :inserted_at
      remove :rejection_reason
      remove :rejected_at
      remove :last_synced_at
      remove :cve_json
      remove :reservation_json
    end

    drop constraint(:cases, "cases_cve_record_id_fkey")

    alter table(:cases) do
      modify :cve_record_id, :uuid
    end

    drop constraint(:cve_records_versions, "cve_records_versions_version_source_id_fkey")

    drop constraint(:cve_records_versions, "cve_records_versions_user_id_fkey")

    alter table(:cve_records_versions) do
      modify :user_id, :uuid
      modify :version_source_id, :uuid
    end

    drop table(:cve_records)

    drop constraint(:case_references_versions, "case_references_versions_user_id_fkey")

    drop table(:case_references_versions)

    drop_if_exists unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :role
      remove :name
      remove :github_handle
      remove :github_id
      remove :email
    end

    drop constraint(:case_comments, "case_comments_author_id_fkey")

    drop constraint(:case_comments, "case_comments_proposal_id_fkey")

    alter table(:case_comments) do
      modify :proposal_id, :uuid
      modify :author_id, :uuid
    end

    drop constraint(:api_keys_versions, "api_keys_versions_user_id_fkey")

    alter table(:api_keys_versions) do
      modify :user_id, :uuid
    end

    drop constraint(:case_proposals, "case_proposals_author_id_fkey")

    drop constraint(:case_proposals, "case_proposals_resolved_by_id_fkey")

    drop constraint(:case_proposals, "case_proposals_parent_proposal_id_fkey")

    alter table(:case_proposals) do
      modify :parent_proposal_id, :uuid
      modify :resolved_by_id, :uuid
      modify :author_id, :uuid
    end

    drop constraint(:case_assignments, "case_assignments_user_id_fkey")

    alter table(:case_assignments) do
      modify :user_id, :uuid
    end

    drop constraint(:users_versions, "users_versions_version_source_id_fkey")

    drop constraint(:users_versions, "users_versions_user_id_fkey")

    alter table(:users_versions) do
      modify :user_id, :uuid
      modify :version_source_id, :uuid
    end

    drop constraint(:case_version_events_versions, "case_version_events_versions_user_id_fkey")

    alter table(:case_version_events_versions) do
      modify :user_id, :uuid
    end

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    alter table(:user_identities) do
      modify :user_id, :uuid
    end

    drop constraint(
           :case_affected_packages_versions,
           "case_affected_packages_versions_user_id_fkey"
         )

    alter table(:case_affected_packages_versions) do
      modify :user_id, :uuid
    end

    drop constraint(:case_impacts_versions, "case_impacts_versions_user_id_fkey")

    alter table(:case_impacts_versions) do
      modify :user_id, :uuid
    end

    drop constraint(:case_credits_versions, "case_credits_versions_user_id_fkey")

    alter table(:case_credits_versions) do
      modify :user_id, :uuid
    end

    drop constraint(:vulnerability_reports, "vulnerability_reports_reporter_id_fkey")

    drop constraint(:vulnerability_reports, "vulnerability_reports_case_id_fkey")

    alter table(:vulnerability_reports) do
      modify :case_id, :uuid
      modify :reporter_id, :uuid
    end

    drop constraint(:case_proposals_versions, "case_proposals_versions_user_id_fkey")

    alter table(:case_proposals_versions) do
      modify :user_id, :uuid
    end

    drop constraint(:case_assignments_versions, "case_assignments_versions_user_id_fkey")

    alter table(:case_assignments_versions) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop constraint(:case_comments, "case_comments_case_id_fkey")

    drop_if_exists index(:case_comments, [:case_id, :inserted_at])

    drop table(:case_comments)

    drop table(:api_keys_versions)

    drop table(:tokens)

    drop table(:capec_attack_pattern_weaknesses)

    drop_if_exists unique_index(:cases, [:cve_record_id], name: "cases_unique_cve_record_index")

    alter table(:cases) do
      remove :cve_record_id
      remove :updated_at
      remove :inserted_at
      remove :published_at
      remove :closed_reason
      remove :internal_notes
      remove :cna_override
      remove :timeline
      remove :date_public
      remove :cvss_v4
      remove :discovery
      remove :solutions_md
      remove :configurations_md
      remove :workarounds_md
      remove :description_md
      remove :title
      remove :state
    end

    drop constraint(:case_proposals, "case_proposals_case_id_fkey")

    alter table(:case_proposals) do
      modify :case_id, :uuid
    end

    drop constraint(:case_assignments, "case_assignments_case_id_fkey")

    alter table(:case_assignments) do
      modify :case_id, :uuid
    end

    drop constraint(:case_package_channels, "case_package_channels_case_id_fkey")

    drop constraint(:case_package_channels, "case_package_channels_affected_package_id_fkey")

    alter table(:case_package_channels) do
      modify :affected_package_id, :uuid
      modify :case_id, :uuid
    end

    drop constraint(:case_weaknesses, "case_weaknesses_case_id_fkey")

    drop constraint(:case_weaknesses, "case_weaknesses_cwe_id_fkey")

    alter table(:case_weaknesses) do
      modify :cwe_id, :bigint
      modify :case_id, :uuid
    end

    drop constraint(:case_affected_packages, "case_affected_packages_case_id_fkey")

    alter table(:case_affected_packages) do
      modify :case_id, :uuid
    end

    drop constraint(:case_version_events, "case_version_events_case_id_fkey")

    drop constraint(:case_version_events, "case_version_events_affected_package_id_fkey")

    drop constraint(:case_version_events, "case_version_events_package_channel_id_fkey")

    alter table(:case_version_events) do
      modify :package_channel_id, :uuid
      modify :affected_package_id, :uuid
      modify :case_id, :uuid
    end

    drop table(:cases)

    drop_if_exists index(:case_proposals, [:case_id, :state])

    drop_if_exists index(:case_proposals, [:target, :target_id, :field_name])

    drop table(:case_proposals)

    drop_if_exists unique_index(:case_assignments, [:case_id, :user_id],
                     name: "case_assignments_unique_case_user_index"
                   )

    drop table(:case_assignments)

    drop table(:users_versions)

    drop table(:case_version_events_versions)

    drop table(:capec_attack_pattern_relationships)

    drop_if_exists unique_index(:user_identities, [:strategy, :uid],
                     name: "user_identities_unique_on_strategy_and_uid_index"
                   )

    drop table(:user_identities)

    drop_if_exists unique_index(
                     :case_package_channels,
                     [:affected_package_id, :channel_type, :package_name],
                     name: "case_package_channels_unique_channel_index"
                   )

    drop table(:case_package_channels)

    drop table(:cwe_metadata)

    drop table(:case_affected_packages_versions)

    drop table(:capec_metadata)

    drop_if_exists unique_index(:case_weaknesses, [:case_id, :cwe_id],
                     name: "case_weaknesses_unique_case_cwe_index"
                   )

    drop table(:case_weaknesses)

    drop table(:case_impacts_versions)

    drop table(:case_affected_packages)

    drop table(:cve_records_versions)

    drop table(:case_credits_versions)

    drop table(:cwe_weaknesses)

    drop table(:case_version_events)

    drop table(:vulnerability_reports)

    drop table(:case_proposals_versions)

    drop table(:case_assignments_versions)

    execute(
      "ALTER TABLE capec_attack_pattern_relationships ALTER CONSTRAINT capec_attack_pattern_relationships_target_capec_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    execute(
      "ALTER TABLE cwe_weakness_relationships ALTER CONSTRAINT cwe_weakness_relationships_target_cwe_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )
  end
end
