defmodule CveManagement.Repo.Migrations.UpdateCveReservations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cve_reservations) do
      remove :reserved_at
      remove :status
      remove :cve_id
      add :reservation_json, :map, null: false
    end

    create unique_index(:cve_reservations, ["(reservation_json->>'cveId')"],
             name: "cve_reservations_unique_cve_id_index"
           )

    alter table(:cve_records) do
      remove :published_at
    end
  end

  def down do
    alter table(:cve_records) do
      add :published_at, :utc_datetime
    end

    drop_if_exists unique_index(:cve_reservations, ["(reservation_json->>'cveId')"],
                     name: "cve_reservations_unique_cve_id_index"
                   )

    alter table(:cve_reservations) do
      remove :reservation_json
      add :cve_id, :text, null: false
      add :status, :text, null: false
      add :reserved_at, :utc_datetime, null: false
    end
  end
end
