defmodule Varsel.Repo.Migrations.AddProviderEmails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_identities) do
      add :email, :text
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    # Existing identity rows predate the column, so seed each with the address
    # the account already carries. Without this an established user opening the
    # email picker would find nothing to choose from until their next sign-in.
    #
    # Only GitHub identities are seeded: users.email was written solely by the
    # GitHub sign-in (it was the only provider), so that address is exactly
    # what GitHub reported and attributing it to any other provider would be
    # inventing a fact.
    execute """
            UPDATE user_identities
            SET email = users.email
            FROM users
            WHERE user_identities.user_id = users.id
              AND user_identities.strategy = 'github'
              AND users.email IS NOT NULL
            """,
            ""
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:user_identities) do
      remove :email
    end
  end
end
