defmodule Varsel.Repo.Migrations.AddCaseSearchVectors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    ALTER TABLE cases ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (
      setweight(to_tsvector('simple', id::text), 'A') ||
      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description_md, '')), 'B') ||
      setweight(to_tsvector('english', coalesce(technical_analysis_md, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(workarounds_md, '')), 'C') ||
      setweight(to_tsvector('english', coalesce(solutions_md, '')), 'C')
    ) STORED
    """)

    execute("""
    CREATE INDEX cases_search_vector_gin ON cases USING GIN (search_vector)
    """)

    execute("""
    CREATE AGGREGATE tsvector_concat_agg(tsvector) (
      SFUNC = tsvector_concat,
      STYPE = tsvector
    )
    """)

    execute("""
    ALTER TABLE case_affected_packages ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (
      to_tsvector('english', coalesce(product, '') || ' ' || coalesce(vendor, ''))
    ) STORED
    """)

    execute("""
    CREATE INDEX case_affected_packages_search_vector_gin ON case_affected_packages USING GIN (search_vector)
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS case_affected_packages_search_vector_gin
    """)

    execute("""
    ALTER TABLE case_affected_packages DROP COLUMN IF EXISTS search_vector
    """)

    execute("""
    DROP AGGREGATE IF EXISTS tsvector_concat_agg(tsvector)
    """)

    execute("""
    DROP INDEX IF EXISTS cases_search_vector_gin
    """)

    execute("""
    ALTER TABLE cases DROP COLUMN IF EXISTS search_vector
    """)
  end
end
