defmodule Varsel.Repo.Migrations.AddNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :notification_email_mode, :text, null: false, default: "immediate"
      add :notification_preferences, {:array, :map}, null: false, default: []
    end

    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :count, :bigint, null: false, default: 1
      add :last_event_at, :utc_datetime_usec, null: false
      add :read_at, :utc_datetime_usec
      add :emailed_at, :utc_datetime_usec
      add :email_requested, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "notifications_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :case_id,
          references(:cases,
            column: :id,
            name: "notifications_case_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :vulnerability_report_id,
          references(:vulnerability_reports,
            column: :id,
            name: "notifications_vulnerability_report_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:notifications, [:user_id, :kind, :case_id, :vulnerability_report_id],
             name: "notifications_unread_per_subject_index",
             nulls_distinct: false,
             where: "(read_at IS NULL)"
           )
  end

  def down do
    drop constraint(:notifications, "notifications_vulnerability_report_id_fkey")

    drop constraint(:notifications, "notifications_case_id_fkey")

    drop constraint(:notifications, "notifications_user_id_fkey")

    drop_if_exists unique_index(
                     :notifications,
                     [:user_id, :kind, :case_id, :vulnerability_report_id],
                     name: "notifications_unread_per_subject_index"
                   )

    drop table(:notifications)

    alter table(:users) do
      remove :notification_preferences
      remove :notification_email_mode
    end
  end
end
