defmodule CveManagement.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:git_hub_reports)

    create table(:git_hub_watched_targets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner, :text, null: false
      add :repo, :text
      add :synced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "git_hub_watched_targets_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:git_hub_watched_targets, [:user_id, :owner, :repo],
             name: "git_hub_watched_targets_unique_target_index"
           )

    create table(:git_hub_app_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :expires_at, :utc_datetime, null: false
      add :status, :text, null: false, default: "valid"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "git_hub_app_tokens_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :encrypted_access_token, :binary, null: false
      add :encrypted_refresh_token, :binary, null: false
    end

    create unique_index(:git_hub_app_tokens, [:user_id],
             name: "git_hub_app_tokens_unique_user_id_index"
           )

    create table(:git_hub_advisory_weaknesses, primary_key: false) do
      add :ghsa_id, :text, null: false, primary_key: true
      add :cwe_id, :bigint, null: false, primary_key: true
    end

    create table(:git_hub_advisories, primary_key: false) do
      add :ghsa_id, :text, null: false, primary_key: true
    end

    alter table(:git_hub_advisory_weaknesses) do
      modify :ghsa_id,
             references(:git_hub_advisories,
               column: :ghsa_id,
               name: "git_hub_advisory_weaknesses_ghsa_id_fkey",
               type: :text,
               prefix: "public"
             )

      modify :cwe_id,
             references(:cwe_weaknesses,
               column: :cwe_id,
               name: "git_hub_advisory_weaknesses_cwe_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:git_hub_advisories) do
      add :cve_id, :text
      add :summary, :text, null: false
      add :description, :text
      add :severity, :text
      add :state, :text, null: false
      add :url, :text, null: false
      add :html_url, :text, null: false
      add :author, :map
      add :publisher, :map
      add :github_created_at, :utc_datetime
      add :github_updated_at, :utc_datetime
      add :github_published_at, :utc_datetime
      add :github_closed_at, :utc_datetime
      add :github_withdrawn_at, :utc_datetime
      add :vulnerabilities, {:array, :map}
      add :cvss_severities, :map
      add :identifiers, {:array, :map}
      add :credits, {:array, :map}
      add :credits_detailed, {:array, :map}
      add :collaborating_users, {:array, :map}
      add :collaborating_teams, {:array, :map}
      add :submission, :map
      add :private_fork, :map
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :fetched_by_user_id,
          references(:users,
            column: :id,
            name: "git_hub_advisories_fetched_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :case_id,
          references(:cases,
            column: :id,
            name: "git_hub_advisories_case_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:git_hub_advisories, "git_hub_advisories_fetched_by_user_id_fkey")

    drop constraint(:git_hub_advisories, "git_hub_advisories_case_id_fkey")

    alter table(:git_hub_advisories) do
      remove :case_id
      remove :fetched_by_user_id
      remove :updated_at
      remove :inserted_at
      remove :processed_at
      remove :private_fork
      remove :submission
      remove :collaborating_teams
      remove :collaborating_users
      remove :credits_detailed
      remove :credits
      remove :identifiers
      remove :cvss_severities
      remove :vulnerabilities
      remove :github_withdrawn_at
      remove :github_closed_at
      remove :github_published_at
      remove :github_updated_at
      remove :github_created_at
      remove :publisher
      remove :author
      remove :html_url
      remove :url
      remove :state
      remove :severity
      remove :description
      remove :summary
      remove :cve_id
    end

    drop constraint(:git_hub_advisory_weaknesses, "git_hub_advisory_weaknesses_ghsa_id_fkey")

    drop constraint(:git_hub_advisory_weaknesses, "git_hub_advisory_weaknesses_cwe_id_fkey")

    alter table(:git_hub_advisory_weaknesses) do
      modify :cwe_id, :bigint
      modify :ghsa_id, :text
    end

    drop table(:git_hub_advisories)

    drop table(:git_hub_advisory_weaknesses)

    drop constraint(:git_hub_app_tokens, "git_hub_app_tokens_user_id_fkey")

    drop_if_exists unique_index(:git_hub_app_tokens, [:user_id],
                     name: "git_hub_app_tokens_unique_user_id_index"
                   )

    drop table(:git_hub_app_tokens)

    drop constraint(:git_hub_watched_targets, "git_hub_watched_targets_user_id_fkey")

    drop_if_exists unique_index(:git_hub_watched_targets, [:user_id, :owner, :repo],
                     name: "git_hub_watched_targets_unique_target_index"
                   )

    drop table(:git_hub_watched_targets)

    # Rollback would require recreating the table manually
  end
end
