defmodule Varsel.Repo.Migrations.MoveProviderHandlesToIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_identities) do
      add :username, :text
    end

    # Carry the handle over before the column holding it goes away. Only GitHub
    # identities are seeded: users.github_handle was written by the GitHub
    # sign-in, so that is whose handle it is.
    execute """
            UPDATE user_identities
            SET username = users.github_handle
            FROM users
            WHERE user_identities.user_id = users.id
              AND user_identities.strategy = 'github'
              AND users.github_handle IS NOT NULL
            """,
            ""

    alter table(:users) do
      remove :github_handle
      remove :github_id
    end

    drop_if_exists unique_index(:users, [:github_id], name: "users_unique_github_id_index")
  end

  def down do
    create unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    alter table(:users) do
      add :github_id, :text
      add :github_handle, :text
    end

    alter table(:user_identities) do
      remove :username
    end
  end
end
