defmodule Varsel.Repo.Migrations.AddCveRecordWithheldState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cve_records) do
      add :withheld_at, :utc_datetime
      add :withhold_reason, :text
    end
  end

  def down do
    alter table(:cve_records) do
      remove :withhold_reason
      remove :withheld_at
    end
  end
end
