defmodule Varsel.Repo.Migrations.DropUserVersionSourceFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:users_versions, "users_versions_version_source_id_fkey")

    alter table(:users_versions) do
      modify :version_source_id, :uuid
    end

    create index(:users_versions, [:version_source_id])
  end

  def down do
    drop_if_exists index(:users_versions, [:version_source_id])

    alter table(:users_versions) do
      modify :version_source_id,
             references(:users,
               column: :id,
               name: "users_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
