defmodule Varsel.Repo.Migrations.AddAccountMerge do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :merged_into_id,
          references(:users,
            column: :id,
            name: "users_merged_into_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:users, "users_merged_into_id_fkey")

    alter table(:users) do
      remove :merged_into_id
    end
  end
end
