defmodule Varsel.Repo.Migrations.AddCveRecordPublishedIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE FUNCTION cve_record_published(cve_json jsonb)
    RETURNS timestamp
    LANGUAGE sql
    IMMUTABLE PARALLEL SAFE
    AS $$
      SELECT (cve_json->'cveMetadata'->>'datePublished')::timestamp
    $$
    """)

    execute("""
    CREATE FUNCTION cve_record_published_quarter(cve_json jsonb)
    RETURNS date
    LANGUAGE sql
    IMMUTABLE PARALLEL SAFE
    AS $$
      SELECT date_trunc('quarter', (cve_json->'cveMetadata'->>'datePublished')::timestamp)::date
    $$
    """)

    execute("""
    CREATE INDEX cve_records_published ON cve_records (cve_record_published(cve_json)) WHERE state = 'published'
    """)

    execute("""
    CREATE INDEX cve_records_published_quarter ON cve_records (cve_record_published_quarter(cve_json)) WHERE state = 'published'
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS cve_records_published_quarter
    """)

    execute("""
    DROP INDEX IF EXISTS cve_records_published
    """)

    execute("""
    DROP FUNCTION IF EXISTS cve_record_published_quarter(jsonb)
    """)

    execute("""
    DROP FUNCTION IF EXISTS cve_record_published(jsonb)
    """)
  end
end
