defmodule Varsel.Repo.Migrations.RenameEmailToNotificationEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Codegen offered `remove :email` plus `add :notification_email`, which would
  # drop every account's address. This renames the column instead, so the data
  # and the index simply carry over under the new name.
  def up do
    rename table(:users), :email, to: :notification_email

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:notification_email],
             name: "users_unique_notification_email_index"
           )
  end

  def down do
    drop_if_exists unique_index(:users, [:notification_email],
                     name: "users_unique_notification_email_index"
                   )

    rename table(:users), :notification_email, to: :email

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end
end
