defmodule Varsel.Repo.Migrations.EnforceOneAccountPerEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_identities) do
      modify :username, :citext
      modify :email, :citext
    end

    alter table(:users) do
      modify :notification_email, :citext
    end

    execute("""
    ALTER TABLE user_identities
    ADD CONSTRAINT user_identities_one_account_per_email
    EXCLUDE USING gist ((lower(email::text)) WITH =, user_id WITH <>)
    WHERE (email IS NOT NULL)
    """)
  end

  def down do
    execute("""
    ALTER TABLE user_identities
    DROP CONSTRAINT user_identities_one_account_per_email
    """)

    alter table(:users) do
      modify :notification_email, :text
    end

    alter table(:user_identities) do
      modify :email, :text
      modify :username, :text
    end
  end
end
